### PR TITLE
FIX: Resolve belga-keywords, country and country keywords issue in belga specific ANP, AFP, DPA, EFE, Itartass parsers

### PR DESCRIPTION
**Pull request by GyanP**
related to [SDBELGA-566] and [SDBELGA-521]

[SDBELGA-566]: https://sofab.atlassian.net/browse/SDBELGA-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDBELGA-521]: https://sofab.atlassian.net/browse/SDBELGA-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by petrjasek — COMMENTED** [review]
so what about the ticket?

**Comment by GyanP** [comment]
> so what about the ticket?

yep please reopen that one SDBELGA-521

**Comment by petrjasek** [comment]
it would be better to create a new one because those were already implemented and shipped as part of previous releases, while this one would be a change/fix. can you write it and link it to previous ones?

**Comment by GyanP** [comment]
> it would be better to create a new one because those were already implemented and shipped as part of previous releases, while this one would be a change/fix. can you write it and link it to previous ones?

Yep, right I created new ticket #SDBELGA-594

**Review by petrjasek — APPROVED** [review]

**Pull request merged**
